# Face_recognition
Điều kiện
py 3.5
